/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "bakery.h"
#include <time.h>
int choosing[32] = {0};
int number[32] = {0};
int num = 0;
char c = 'a';
struct BAKERY *
get_number_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;
	int ind = num++, max = 0;
	argp->pid = ind;
	choosing[ind] = 1;
	for (int i = 0; i < 32; i++)
		if (number[i] > max)
			max = number[i];
	number[ind] = max + 1;
	argp->num = number[ind];
	choosing[ind] = 0;
	result.pid = argp->pid;
	result.num = argp->num;
	return &result;
}
struct BAKERY *
bakery_service_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;
	clock_t t_start;
	int flag;
	for (int j = 0; j < 32; j++)
	{
		while (choosing[j]) {};
		flag = 1;
		t_start = clock();
		while (flag && number[j] != 0 && (number[j] < argp->num || (number[j] == argp->num && j < argp->pid)))
			if ((clock() - t_start) / CLOCKS_PER_SEC)
				flag = 0;
		if (!flag)
			continue;
	}
	argp->res = c++;
	if (c > 'z')
		c = 'a';
	printf("Client id = %d, num = %d, res = %c\n", argp->pid, argp->num, argp->res);
	number[argp->pid] = 0;
	result.res = argp->res;
	return &result;
}
